version: 2.1
jobs:
  documentation:
    working_directory: ~/dspace-cli
    docker:
      - image: circleci/ruby:2.6.6
      - image: jrgriffiniii/dspace-docker:testing
    steps:
      - checkout
      - run:
          name: Install the RVM
          command: |
            gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
            \curl -sSL https://get.rvm.io | bash -s stable
            source /home/circleci/.rvm/scripts/rvm
      - run:
          name: Install the deb package dependencies
          command: |
            sudo apt-get update -y
            sudo apt-get install -y gawk openjdk-8-jre-headless
      - run:
          name: Set JRuby version to 9.2.13.0
          command: |
            source /home/circleci/.rvm/scripts/rvm
            rvm install 9.2.13.0
            echo . $(rvm 9.2.13.0 do rvm env --path) >> $BASH_ENV
      - run:
          name: Install bundler
          command: gem install -v 2.1.4 bundler
      - run:
          name: Install the dependencies
          command: bundle install
      - run:
          name: Build the YARD documentation
          command: bundle exec yardoc
  lint:
    working_directory: ~/dspace-cli
    docker:
      - image: circleci/ruby:2.6.6
      - image: jrgriffiniii/dspace-docker:testing
    steps:
      - checkout
      - run:
          name: Install the RVM
          command: |
            gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
            \curl -sSL https://get.rvm.io | bash -s stable
            source /home/circleci/.rvm/scripts/rvm
      - run:
          name: Install the deb package dependencies
          command: |
            sudo apt-get update -y
            sudo apt-get install -y gawk openjdk-8-jre-headless
      - run:
          name: Set JRuby version to 9.2.13.0
          command: |
            source /home/circleci/.rvm/scripts/rvm
            rvm install 9.2.13.0
            echo . $(rvm 9.2.13.0 do rvm env --path) >> $BASH_ENV
      - run:
          name: Install bundler
          command: gem install -v 2.1.4 bundler
      - run:
          name: Install the dependencies
          command: bundle install
      - run:
          name: Validate the code formatting and style
          command: bundle exec rubocop cli.thor dspace.rb dspace/cli/**/*rb

workflows:
  ci:
    jobs:
      - documentation
      - lint
