version: 2.1
jobs:
  documentation:
    parameters:
      ruby_version:
        type: string
    working_directory: ~/dspace-cli
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Set JRuby version
          command: |
            rvm install << parameters.ruby_version >>
            echo . $(rvm << parameters.ruby_version >> do rvm env --path) >> $BASH_ENV
      - run:
          name: Install bundler
          command: gem install -v 1.10.6 bundler
      - run:
          name: Install the dependencies
          command: bundle install
      - run:
          name: Build the YARD documentation
          command: bundle exec yardoc
workflows:
  ci:
    jobs:
      - documentation:
          name: jruby9.2.11
          ruby_version: "cli-9.2.11.1"
      - documentation:
          name: jruby9.2.13
          ruby_version: "cli-9.2.13.0"
