version: 2.1
jobs:
  documentation:
    working_directory: ~/dspace-cli
    docker:
      - image: circleci/jruby:9.2.13.0
      - image: jrgriffiniii/dspace-docker:testing
    steps:
      - checkout
      - run:
          name: Install bundler
          command: gem install -v 2.1.4 bundler
      - run:
          name: Install the dependencies
          command: bundle install
      - run:
          name: Build the YARD documentation
          command: bundle exec yardoc
  lint:
    working_directory: ~/dspace-cli
    docker:
      - image: circleci/jruby:9.2.13.0
      - image: jrgriffiniii/dspace-docker:testing
    steps:
      - checkout
      - run:
          name: Install bundler
          command: gem install -v 2.1.4 bundler
      - run:
          name: Install the dependencies
          command: bundle install
      - run:
          name: Validate the code formatting and style
          command: bundle exec rubocop cli.thor dspace.rb dspace/cli/**/*rb

workflows:
  ci:
    jobs:
      - documentation
      - lint
